// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionApi.Persistance.Context;

#nullable disable

namespace OnionApi.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124172750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");

                    b.Property<int>("ProductsID")
                        .HasColumnType("int");

                    b.HasKey("CategoriesID", "ProductsID");

                    b.HasIndex("ProductsID");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(3494),
                            IsDeleted = false,
                            Name = "Movies"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(3546),
                            IsDeleted = false,
                            Name = "Electronics, Garden & Garden"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(3617),
                            IsDeleted = true,
                            Name = "Automotive"
                        });
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(4628),
                            IsDeleted = false,
                            Name = "Elektronik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(4632),
                            IsDeleted = false,
                            Name = "Elektronik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(4633),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priorty = 1
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 369, DateTimeKind.Local).AddTicks(4634),
                            IsDeleted = false,
                            Name = "Kadın",
                            ParentId = 0,
                            Priorty = 1
                        });
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 371, DateTimeKind.Local).AddTicks(418),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsDeleted = false,
                            Title = "Refined Steel Bike"
                        },
                        new
                        {
                            ID = 1,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 371, DateTimeKind.Local).AddTicks(395),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IsDeleted = false,
                            Title = "Handmade Rubber Mouse"
                        },
                        new
                        {
                            ID = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 371, DateTimeKind.Local).AddTicks(435),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsDeleted = true,
                            Title = "Small Plastic Soap"
                        });
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 372, DateTimeKind.Local).AddTicks(4206),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 65.35794409705332m,
                            IsDeleted = false,
                            Price = 90.34m,
                            Title = "Sleek Fresh Bike"
                        },
                        new
                        {
                            ID = 2,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 24, 20, 27, 50, 372, DateTimeKind.Local).AddTicks(4239),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 105.380401695661912m,
                            IsDeleted = false,
                            Price = 22.50m,
                            Title = "Handcrafted Cotton Shirt"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("OnionApi.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Detail", b =>
                {
                    b.HasOne("OnionApi.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("OnionApi.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OnionApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
